sudo: required
services:
  - docker

before_install:
  - docker build -t mrityunjay2docker/multi_container_app_client -f ./client/Dockerfile.dev .

script:
  - docker run mrityunjay2docker/multi_container_app_client -e CI=true npm run test -- --coverage
  