version: '3'
services:
  postgres-server:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres_password

  redis-server:
    image: 'redis:latest'
    
  # yay! nginx
  nginx:
    depends_on:
      - client
      - express_server
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '5051:80'
  
  client:
    stdin_open: true
    build:
      context: './client'
      dockerfile: 'Dockerfile.dev'
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./client:/app
      

  expressserver:
    restart: always
    build: 
      context: './server'
      dockerfile: 'Dockerfile.dev'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
      - PGPORT=5432
     
  worker:
    build: 
      context: './worker'
      dockerfile: 'Dockerfile.dev'
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379

# this is all about the multi container application
